package knowledge

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"os"
	"path/filepath"
	"strings"
)

const GeneratedIndex = "<!-- Generated by gnosis;"

type concept struct {
	Path        string
	Title       string
	Description string
}

type indexEntry struct {
	Title       string
	Description string
	URL         string
}

type indexData struct {
	Root        bool
	Title       string
	Description string
	Entries     []indexEntry
}

func MarkdownText(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	return strings.NewReplacer("\\", "\\\\", "[", "\\[", "]", "\\]", "*", "\\*", "_", "\\_").Replace(s)
}

func linkPath(s string) string {
	parts := strings.Split(s, "/")
	for i := range parts {
		parts[i] = url.PathEscape(parts[i])
	}
	return strings.Join(parts, "/")
}

func GenerateIndexes(dir string, force bool) error {
	m, policy, concepts, err := scanPackage(dir, false)
	if err != nil {
		return err
	}
	tmpl, err := loadIndexTemplate(dir, policy.IndexTemplate)
	if err != nil {
		return err
	}
	dirs := map[string][]indexEntry{".": {}}
	if err := filepath.WalkDir(dir, func(file string, entry fs.DirEntry, err error) error {
		if err != nil || !entry.IsDir() {
			return err
		}
		relative, err := filepath.Rel(dir, file)
		if err != nil {
			return err
		}
		dirs[filepath.ToSlash(relative)] = []indexEntry{}
		return nil
	}); err != nil {
		return err
	}
	for _, c := range concepts {
		parent := filepath.ToSlash(filepath.Dir(c.Path))
		dirs[parent] = append(dirs[parent], indexEntry{
			Title: MarkdownText(c.Title), Description: MarkdownText(c.Description),
			URL: linkPath(filepath.Base(c.Path)),
		})
		for child := parent; child != "."; child = filepath.ToSlash(filepath.Dir(child)) {
			parent := filepath.ToSlash(filepath.Dir(child))
			if _, exists := dirs[parent]; !exists {
				dirs[parent] = []indexEntry{}
			}
		}
	}
	for _, child := range SortedKeys(dirs) {
		if child == "." {
			continue
		}
		parent := filepath.ToSlash(filepath.Dir(child))
		dirs[parent] = append(dirs[parent], indexEntry{
			Title: MarkdownText(filepath.Base(child)), URL: linkPath(filepath.Base(child)) + "/",
		})
	}
	outputs := map[string][]byte{}
	for _, relative := range SortedKeys(dirs) {
		title := filepath.Base(relative)
		description := ""
		if relative == "." {
			title, description = m.Package, m.Description
		}
		var output bytes.Buffer
		err := tmpl.Execute(&output, indexData{
			Root: relative == ".", Title: MarkdownText(title),
			Description: MarkdownText(description), Entries: dirs[relative],
		})
		if err != nil {
			return err
		}
		indexPath := filepath.ToSlash(filepath.Join(relative, "index.md"))
		if err := validateReserved(indexPath, output.Bytes()); err != nil {
			return fmt.Errorf("index template output: %w", err)
		}
		file := filepath.Join(dir, relative, "index.md")
		old, err := ReadRegular(file)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err == nil && !bytes.Contains(old, []byte(GeneratedIndex)) && !force {
			return fmt.Errorf("%s is hand-authored; use index --force to replace it", file)
		}
		outputs[file] = append([]byte{}, output.Bytes()...)
	}
	for _, file := range SortedKeys(outputs) {
		if err := WriteAtomic(file, outputs[file]); err != nil {
			return err
		}
	}
	return nil
}
