package main

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"
	"unicode/utf8"

	"github.com/santhosh-tekuri/jsonschema/v5"
)

//go:embed assets/* skills/*/SKILL.md
var assets embed.FS

const generatedIndex = "<!-- Generated by gnosis;"

type concept struct {
	Path        string
	Title       string
	Description string
}

type indexEntry struct {
	Title       string
	Description string
	URL         string
}

type indexData struct {
	Root        bool
	Title       string
	Description string
	Entries     []indexEntry
}

func safePath(root, relative string) (string, error) {
	if err := validPath(relative); err != nil {
		return "", err
	}
	current := root
	for _, part := range strings.Split(relative, "/") {
		current = filepath.Join(current, part)
		info, err := os.Lstat(current)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return "", err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("symlink is not allowed: %s", current)
		}
	}
	return filepath.Join(root, filepath.FromSlash(relative)), nil
}

func loadStandard(dir string) (standard, *jsonschema.Schema, error) {
	var policy standard
	if err := readData(filepath.Join(dir, "standard.yml"), &policy); err != nil {
		return policy, nil, err
	}
	if policy.GnosisVersion != 1 || policy.MaxWords < 0 {
		return policy, nil, errors.New("standard.yml requires gnosis_version 1 and nonnegative max_words")
	}
	schemaPath, err := safePath(dir, policy.Schema)
	if err != nil {
		return policy, nil, err
	}
	if _, err := safePath(dir, policy.IndexTemplate); err != nil {
		return policy, nil, err
	}
	compiler := jsonschema.NewCompiler()
	compiler.LoadURL = func(location string) (io.ReadCloser, error) {
		u, err := url.Parse(location)
		if err != nil {
			return nil, err
		}
		if u.Scheme != "file" || u.Host != "" {
			return nil, fmt.Errorf("schema references must be package-local files: %s", location)
		}
		relative, err := filepath.Rel(dir, filepath.FromSlash(u.Path))
		if err != nil {
			return nil, err
		}
		file, err := safePath(dir, filepath.ToSlash(relative))
		if err != nil {
			return nil, err
		}
		data, err := readRegular(file)
		if err != nil {
			return nil, err
		}
		return io.NopCloser(bytes.NewReader(data)), nil
	}
	schemaURL := (&url.URL{Scheme: "file", Path: filepath.ToSlash(schemaPath)}).String()
	schema, err := compiler.Compile(schemaURL)
	return policy, schema, err
}

func frontmatter(data []byte) (map[string]any, string, error) {
	if !utf8.Valid(data) {
		return nil, "", errors.New("document must be UTF-8")
	}
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	lines := strings.Split(text, "\n")
	if len(lines) == 0 || lines[0] != "---" {
		return nil, "", errors.New("concept must start with YAML frontmatter (---)")
	}
	for i := 1; i < len(lines); i++ {
		if lines[i] != "---" {
			continue
		}
		fields := map[string]any{}
		if err := decode([]byte(strings.Join(lines[1:i], "\n")), &fields); err != nil {
			return nil, "", fmt.Errorf("frontmatter: %w", err)
		}
		if fields == nil {
			return nil, "", errors.New("frontmatter must be a mapping")
		}
		return fields, strings.Join(lines[i+1:], "\n"), nil
	}
	return nil, "", errors.New("frontmatter is missing its closing ---")
}

func validateReserved(relative string, data []byte) error {
	if !utf8.Valid(data) {
		return fmt.Errorf("%s must be UTF-8", relative)
	}
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	if strings.HasPrefix(text, "---\n") {
		if relative != "index.md" {
			return fmt.Errorf("%s: only the bundle-root index.md may contain frontmatter", relative)
		}
		fields, _, err := frontmatter(data)
		if err != nil {
			return err
		}
		if len(fields) != 1 {
			return errors.New("root index frontmatter may contain only okf_version")
		}
		if value, ok := fields["okf_version"].(string); !ok || strings.TrimSpace(value) == "" {
			return errors.New("root index requires a string okf_version")
		}
	}
	if filepath.Base(relative) == "log.md" {
		for _, line := range strings.Split(text, "\n") {
			if strings.HasPrefix(line, "## ") {
				if _, err := time.Parse("2006-01-02", strings.TrimPrefix(line, "## ")); err != nil {
					return fmt.Errorf("%s: log date headings must be ## YYYY-MM-DD", relative)
				}
			}
		}
	}
	return nil
}

func scanPackage(dir string, checkIndexes bool) (manifest, standard, []concept, error) {
	m, err := readManifest(dir)
	if err != nil {
		return m, standard{}, nil, err
	}
	policy, schema, err := loadStandard(dir)
	if err != nil {
		return m, policy, nil, err
	}
	for _, relative := range policy.RequiredFiles {
		file, err := safePath(dir, relative)
		if err != nil {
			return m, policy, nil, err
		}
		if _, err := readRegular(file); err != nil {
			return m, policy, nil, fmt.Errorf("required file: %w", err)
		}
	}
	concepts := []concept{}
	err = filepath.WalkDir(dir, func(file string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		relative, err := filepath.Rel(dir, file)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		if err := validPath(relative); err != nil {
			return err
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("%s: symlinks are not supported in packages", relative)
		}
		if entry.IsDir() {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("%s: package entries must be regular files", relative)
		}
		if filepath.Ext(file) != ".md" {
			return nil
		}
		data, err := readRegular(file)
		if err != nil {
			return err
		}
		if entry.Name() == "index.md" || entry.Name() == "log.md" {
			if entry.Name() == "index.md" && !checkIndexes {
				return nil
			}
			return validateReserved(relative, data)
		}
		fields, body, err := frontmatter(data)
		if err != nil {
			return fmt.Errorf("%s: %w", relative, err)
		}
		kind, ok := fields["type"].(string)
		if !ok || strings.TrimSpace(kind) == "" {
			return fmt.Errorf("%s: OKF requires a nonempty string type", relative)
		}
		// Normalize YAML timestamps and numbers to JSON Schema's data model.
		jsonBytes, err := json.Marshal(fields)
		if err != nil {
			return fmt.Errorf("%s: frontmatter must use JSON-compatible keys and values: %w", relative, err)
		}
		var value any
		if err := json.Unmarshal(jsonBytes, &value); err != nil {
			return err
		}
		if err := schema.Validate(value); err != nil {
			return fmt.Errorf("%s: package frontmatter policy: %w", relative, err)
		}
		for _, heading := range policy.RequiredHeads {
			if !strings.Contains("\n"+body+"\n", "\n"+heading+"\n") {
				return fmt.Errorf("%s: required heading %q is missing", relative, heading)
			}
		}
		if policy.MaxWords > 0 && len(strings.Fields(body)) > policy.MaxWords {
			return fmt.Errorf("%s: body exceeds max_words %d", relative, policy.MaxWords)
		}
		title, _ := fields["title"].(string)
		if title == "" {
			title = strings.TrimSuffix(entry.Name(), ".md")
		}
		description, _ := fields["description"].(string)
		concepts = append(concepts, concept{Path: relative, Title: title, Description: description})
		return nil
	})
	return m, policy, concepts, err
}

func markdownText(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	return strings.NewReplacer("\\", "\\\\", "[", "\\[", "]", "\\]", "*", "\\*", "_", "\\_").Replace(s)
}

func linkPath(s string) string {
	parts := strings.Split(s, "/")
	for i := range parts {
		parts[i] = url.PathEscape(parts[i])
	}
	return strings.Join(parts, "/")
}

func generateIndexes(dir string, force bool) error {
	m, policy, concepts, err := scanPackage(dir, false)
	if err != nil {
		return err
	}
	templateFile, err := safePath(dir, policy.IndexTemplate)
	if err != nil {
		return err
	}
	data, err := readRegular(templateFile)
	if err != nil {
		return err
	}
	tmpl, err := template.New("index").Option("missingkey=error").Parse(string(data))
	if err != nil {
		return err
	}
	dirs := map[string][]indexEntry{".": {}}
	if err := filepath.WalkDir(dir, func(file string, entry fs.DirEntry, err error) error {
		if err != nil || !entry.IsDir() {
			return err
		}
		relative, err := filepath.Rel(dir, file)
		if err != nil {
			return err
		}
		dirs[filepath.ToSlash(relative)] = []indexEntry{}
		return nil
	}); err != nil {
		return err
	}
	for _, c := range concepts {
		parent := filepath.ToSlash(filepath.Dir(c.Path))
		dirs[parent] = append(dirs[parent], indexEntry{
			Title: markdownText(c.Title), Description: markdownText(c.Description),
			URL: linkPath(filepath.Base(c.Path)),
		})
		for child := parent; child != "."; child = filepath.ToSlash(filepath.Dir(child)) {
			parent := filepath.ToSlash(filepath.Dir(child))
			if _, exists := dirs[parent]; !exists {
				dirs[parent] = []indexEntry{}
			}
		}
	}
	for _, child := range sortedKeys(dirs) {
		if child == "." {
			continue
		}
		parent := filepath.ToSlash(filepath.Dir(child))
		dirs[parent] = append(dirs[parent], indexEntry{
			Title: markdownText(filepath.Base(child)), URL: linkPath(filepath.Base(child)) + "/",
		})
	}
	outputs := map[string][]byte{}
	for _, relative := range sortedKeys(dirs) {
		title := filepath.Base(relative)
		description := ""
		if relative == "." {
			title, description = m.Package, m.Description
		}
		var output bytes.Buffer
		err := tmpl.Execute(&output, indexData{
			Root: relative == ".", Title: markdownText(title),
			Description: markdownText(description), Entries: dirs[relative],
		})
		if err != nil {
			return err
		}
		indexPath := filepath.ToSlash(filepath.Join(relative, "index.md"))
		if err := validateReserved(indexPath, output.Bytes()); err != nil {
			return fmt.Errorf("index template output: %w", err)
		}
		file := filepath.Join(dir, relative, "index.md")
		old, err := readRegular(file)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err == nil && !bytes.Contains(old, []byte(generatedIndex)) && !force {
			return fmt.Errorf("%s is hand-authored; use index --force to replace it", file)
		}
		outputs[file] = append([]byte{}, output.Bytes()...)
	}
	for _, file := range sortedKeys(outputs) {
		if err := writeAtomic(file, outputs[file]); err != nil {
			return err
		}
	}
	return nil
}

func scaffoldPackage(dir string, m manifest) error {
	if err := m.validate(); err != nil {
		return err
	}
	if err := os.Mkdir(dir, 0o755); err != nil {
		return err
	}
	for _, name := range []string{"standard.yml", "frontmatter.schema.json", "index.tmpl"} {
		data, err := assets.ReadFile("assets/" + name)
		if err != nil {
			return err
		}
		if err := writeAtomic(filepath.Join(dir, name), data); err != nil {
			return err
		}
	}
	if err := writeData(filepath.Join(dir, "package.yml"), m); err != nil {
		return err
	}
	return generateIndexes(dir, false)
}
