package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func initWorkspace(w workspace, install bool) error {
	if _, err := os.Lstat(w.dir); !errors.Is(err, os.ErrNotExist) {
		if err != nil {
			return err
		}
		return fmt.Errorf("%s already exists; initialization never overwrites it", w.dir)
	}
	if install {
		if err := installSkills(w.root, true); err != nil {
			return err
		}
	}
	if err := os.Mkdir(w.dir, 0o755); err != nil {
		return err
	}
	if err := writeAtomic(filepath.Join(w.dir, "gnosis.yml"), []byte("gnosis_version: 1\n")); err != nil {
		return err
	}
	if err := writeData(filepath.Join(w.dir, "registry.yml"), registry{}); err != nil {
		return err
	}
	lock := lockfile{GnosisVersion: 1, Packages: map[string]lockedPackage{}}
	if err := writeData(filepath.Join(w.dir, "gnosis.lock"), lock); err != nil {
		return err
	}
	if err := rootIndex(w); err != nil {
		return err
	}
	if install {
		return installSkills(w.root, false)
	}
	return nil
}

func installSkills(root string, checkOnly bool) error {
	names := []string{"gnosis-navigate", "gnosis-update", "gnosis-cli"}
	for _, name := range names {
		file, err := safePath(root, ".agents/skills/"+name+"/SKILL.md")
		if err != nil {
			return err
		}
		data, err := assets.ReadFile("skills/" + name + "/SKILL.md")
		if err != nil {
			return err
		}
		existing, err := readRegular(file)
		if err == nil && !bytes.Equal(existing, data) {
			return fmt.Errorf("%s already exists with different content; refusing to overwrite", file)
		}
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if checkOnly {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
			return err
		}
		if err := writeAtomic(file, data); err != nil {
			return err
		}
	}
	return nil
}

func localPackages(w workspace) (map[string]manifest, error) {
	entries, err := os.ReadDir(w.dir)
	if err != nil {
		return nil, err
	}
	packages := map[string]manifest{}
	for _, entry := range entries {
		if entry.Type()&os.ModeSymlink != 0 {
			return nil, fmt.Errorf("%s: symlink is not allowed in the knowledge root", entry.Name())
		}
		if !entry.IsDir() {
			continue
		}
		if err := validName(entry.Name()); err != nil {
			return nil, err
		}
		m, err := readManifest(filepath.Join(w.dir, entry.Name()))
		if err != nil {
			return nil, err
		}
		if m.Package != entry.Name() {
			return nil, fmt.Errorf("%s: manifest package must match its directory", entry.Name())
		}
		packages[m.Package] = m
	}
	return packages, nil
}

func rootIndex(w workspace) error {
	packages, err := localPackages(w)
	if err != nil {
		return err
	}
	var text strings.Builder
	text.WriteString("<!-- Generated by gnosis; edit package descriptions instead. -->\n\n# Knowledge packages\n")
	for _, name := range sortedKeys(packages) {
		m := packages[name]
		fmt.Fprintf(&text, "\n* [%s](%s/index.md) - %s\n",
			name, name, markdownText(m.Description),
		)
	}
	file := filepath.Join(w.dir, "index.md")
	old, err := readRegular(file)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err == nil && !bytes.Contains(old, []byte(generatedIndex)) {
		return errors.New("gnosis/index.md is hand-authored; move it aside before regenerating the root index")
	}
	return writeAtomic(file, []byte(text.String()))
}

func dependencyOrder(packages map[string]manifest, names []string) ([]string, error) {
	state := map[string]int{}
	order := []string{}
	var visit func(string) error
	visit = func(name string) error {
		if state[name] == 1 {
			return fmt.Errorf("dependency cycle at %s", name)
		}
		if state[name] == 2 {
			return nil
		}
		m, exists := packages[name]
		if !exists {
			return fmt.Errorf("missing dependency %s; discover and add it first", name)
		}
		state[name] = 1
		for _, dep := range m.Dependencies {
			if err := visit(dep); err != nil {
				return fmt.Errorf("%s: %w", name, err)
			}
		}
		state[name] = 2
		order = append(order, name)
		return nil
	}
	for _, name := range names {
		if err := visit(name); err != nil {
			return nil, err
		}
	}
	return order, nil
}

func validateWorkspace(w workspace, names []string) error {
	packages, err := localPackages(w)
	if err != nil {
		return err
	}
	lock, err := readLock(w.dir)
	if err != nil {
		return err
	}
	locked := map[string]manifest{}
	for name, p := range lock.Packages {
		if _, exists := packages[name]; !exists {
			return fmt.Errorf("locked package %s is missing; run gnosis restore", name)
		}
		locked[name] = manifest{Dependencies: p.Dependencies}
	}
	for name, m := range packages {
		if _, exists := locked[name]; !exists {
			locked[name] = m
		}
	}
	if _, err := dependencyOrder(locked, sortedKeys(locked)); err != nil {
		return fmt.Errorf("lock dependency graph: %w", err)
	}
	if len(names) == 0 {
		names = sortedKeys(packages)
	}
	order, err := dependencyOrder(packages, names)
	if err != nil {
		return err
	}
	for _, name := range order {
		if _, _, _, err := scanPackage(filepath.Join(w.dir, name), true); err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
	}
	return nil
}

func generateCodeowners(w workspace) error {
	packages, err := localPackages(w)
	if err != nil {
		return err
	}
	lock, err := readLock(w.dir)
	if err != nil {
		return err
	}
	file := ""
	data := []byte{}
	for _, candidate := range []string{".github/CODEOWNERS", "CODEOWNERS", "docs/CODEOWNERS"} {
		candidatePath, err := safePath(w.root, candidate)
		if err != nil {
			return err
		}
		content, err := readRegular(candidatePath)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}
		file, data = candidatePath, content
		break
	}
	if file == "" {
		file, err = safePath(w.root, ".github/CODEOWNERS")
		if err != nil {
			return err
		}
	}
	const begin = "# BEGIN GNOSIS OWNERS"
	const end = "# END GNOSIS OWNERS"
	text := string(data)
	start, finish := strings.Index(text, begin), strings.Index(text, end)
	if (start < 0) != (finish < 0) || finish < start {
		return errors.New("malformed gnosis CODEOWNERS block; repair it before regeneration")
	}
	if strings.Count(text, begin) > 1 || strings.Count(text, end) > 1 {
		return errors.New("duplicate gnosis CODEOWNERS blocks")
	}
	var block strings.Builder
	block.WriteString(begin + "\n")
	for _, name := range sortedKeys(packages) {
		if _, imported := lock.Packages[name]; imported {
			continue
		}
		handle, err := packages[name].Owner.handle()
		if err != nil {
			return err
		}
		fmt.Fprintf(&block, "/gnosis/%s/ %s\n", name, handle)
	}
	block.WriteString(end)
	if start >= 0 {
		text = text[:start] + block.String() + text[finish+len(end):]
	} else {
		text = strings.TrimRight(text, "\n") + "\n\n" + block.String() + "\n"
		text = strings.TrimLeft(text, "\n")
	}
	if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
		return err
	}
	return writeAtomic(file, []byte(text))
}

func commitMetadata(ctx context.Context, w workspace, name string) error {
	if err := rootIndex(w); err != nil {
		return err
	}
	if _, err := git(ctx, w.root, "add", "--", "gnosis/gnosis.lock", "gnosis/index.md"); err != nil {
		return err
	}
	diff, err := git(ctx, w.root, "diff", "--cached", "--name-only")
	if err != nil {
		return err
	}
	if diff == "" {
		return nil
	}
	for _, file := range strings.Split(diff, "\n") {
		if file != "gnosis/gnosis.lock" && file != "gnosis/index.md" {
			return fmt.Errorf("refusing to include unrelated staged file %s in lock commit", file)
		}
	}
	_, err = git(ctx, w.root, "commit", "-m", "gnosis: lock "+name)
	return err
}
