use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Component, Path};

use anyhow::{Context, Result, bail, ensure};
use serde::{Deserialize, Serialize};
use serde_yaml_ng::{Mapping, Value};

pub const MARKER: &str = "<!-- Generated by gnosis -->";
pub const MAX_FILE: usize = 16 * 1024 * 1024;
pub const MAX_TREE: usize = 256 * 1024 * 1024;
pub type Tree = BTreeMap<String, Vec<u8>>;

#[derive(Default)]
pub struct ConceptMetadata {
    pub kind: Option<String>,
    pub title: Option<String>,
    pub description: Option<String>,
    pub resource: Option<String>,
    pub tags: Vec<String>,
    pub sources: Vec<String>,
    pub fields: Vec<String>,
}

impl ConceptMetadata {
    fn values(&self, name: &str) -> Result<Mapping> {
        let mut metadata = Mapping::new();
        for (key, value) in [
            ("type", &self.kind),
            ("title", &self.title),
            ("description", &self.description),
            ("resource", &self.resource),
        ] {
            if let Some(value) = value {
                metadata.insert(Value::from(key), Value::from(value.clone()));
            }
        }
        if !self.tags.is_empty() {
            metadata.insert(Value::from("tags"), serde_yaml_ng::to_value(&self.tags)?);
        }
        if !self.sources.is_empty() {
            let sources: Vec<_> = self
                .sources
                .iter()
                .map(|source| BTreeMap::from([("resource", source)]))
                .collect();
            metadata.insert(Value::from("sources"), serde_yaml_ng::to_value(sources)?);
        }
        for field in &self.fields {
            let (key, yaml) = field.split_once('=').context("--field requires KEY=YAML")?;
            ensure!(
                !key.trim().is_empty() && key.trim() == key,
                "metadata field needs a nonempty key without surrounding whitespace"
            );
            ensure!(
                !metadata.contains_key(key),
                "metadata field {key:?} was supplied more than once"
            );
            let value: Value = serde_yaml_ng::from_str(yaml)
                .with_context(|| format!("invalid YAML for field {key}"))?;
            metadata.insert(Value::from(key), value);
        }
        if !metadata.contains_key("type") {
            metadata.insert(Value::from("type"), Value::from("Reference"));
        }
        if !metadata.contains_key("title") {
            let title = name.replace(['-', '_'], " ");
            let mut chars = title.chars();
            let title = match chars.next() {
                Some(first) => format!("{}{}", first.to_uppercase(), chars.as_str()),
                None => bail!("name cannot be empty"),
            };
            metadata.insert(Value::from("title"), Value::from(title));
        }
        let title = metadata
            .get("title")
            .and_then(Value::as_str)
            .context("title must be a string")?;
        ensure!(
            !title.trim().is_empty() && !title.contains(['\n', '\r']),
            "title must be a nonempty single line"
        );
        ensure!(
            metadata
                .get("type")
                .and_then(Value::as_str)
                .is_some_and(|kind| !kind.trim().is_empty()),
            "concept needs a nonempty string type"
        );
        Ok(metadata)
    }

    pub fn render_directory(&self, path: &str) -> Result<Vec<u8>> {
        let name = Path::new(path)
            .file_name()
            .and_then(|name| name.to_str())
            .context("invalid directory name")?;
        let bytes = serde_yaml_ng::to_string(&self.values(name)?)?.into_bytes();
        ensure!(bytes.len() <= MAX_FILE, "directory metadata exceeds 16 MiB");
        Ok(bytes)
    }

    pub fn render(&self, path: &str, body: Option<&str>) -> Result<Vec<u8>> {
        let stem = Path::new(path)
            .file_stem()
            .and_then(|stem| stem.to_str())
            .context("invalid concept filename")?;
        let metadata = self.values(stem)?;
        let title = metadata
            .get("title")
            .and_then(Value::as_str)
            .context("title must be a string")?;
        let default_body = format!("# {}\n", escape(title));
        let document = format!(
            "---\n{}---\n{}",
            serde_yaml_ng::to_string(&metadata)?,
            body.unwrap_or(&default_body)
        );
        ensure!(document.len() <= MAX_FILE, "new concept exceeds 16 MiB");
        let bytes = document.into_bytes();
        validate_okf(&Tree::from([(path.to_owned(), bytes.clone())]))?;
        Ok(bytes)
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Source {
    pub repository: String,
    #[serde(rename = "ref")]
    pub reference: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Manifest {
    pub format: u32,
    #[serde(default)]
    pub packages: BTreeSet<String>,
    #[serde(default)]
    pub sources: BTreeMap<String, Source>,
    #[serde(default)]
    pub dependencies: BTreeMap<String, String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Package {
    pub name: String,
    pub owner: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub dependencies: BTreeSet<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedPackage {
    pub source: String,
    pub location: Source,
    pub commit: String,
    pub dependencies: BTreeSet<String>,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Lock {
    pub format: u32,
    #[serde(default)]
    pub requirements: BTreeMap<String, String>,
    #[serde(default)]
    pub sources: BTreeMap<String, Source>,
    #[serde(default)]
    pub packages: BTreeMap<String, LockedPackage>,
}

pub fn decode<T: for<'de> Deserialize<'de>>(bytes: &[u8]) -> Result<T> {
    ensure!(bytes.len() <= MAX_FILE, "metadata exceeds 16 MiB");
    Ok(toml::from_str(std::str::from_utf8(bytes)?)?)
}

pub fn encode(value: &impl Serialize) -> Result<Vec<u8>> {
    Ok(toml::to_string_pretty(value)?.into_bytes())
}

pub fn name(value: &str) -> Result<()> {
    ensure!(
        !value.is_empty()
            && value.len() <= 64
            && value.split('-').all(|part| !part.is_empty()
                && part
                    .bytes()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())),
        "invalid name {value:?}: use lowercase letters/digits separated by single hyphens"
    );
    Ok(())
}

pub fn safe_path(value: &str) -> Result<()> {
    ensure!(
        !value.is_empty()
            && !value.contains(['\\', '\0', '\n', '\r', ':'])
            && value.split('/').all(|part| !part.is_empty()
                && part != "."
                && part != ".."
                && !part.eq_ignore_ascii_case(".git"))
            && Path::new(value)
                .components()
                .all(|part| matches!(part, Component::Normal(_))),
        "unsafe package path {value:?}"
    );
    Ok(())
}

pub fn validate_source(source: &Source) -> Result<()> {
    ensure!(!source.repository.is_empty(), "empty source repository");
    ensure!(
        !source.repository.starts_with('-') && !source.repository.contains("::"),
        "unsupported Git repository syntax"
    );
    if source.repository.starts_with("https://") || source.repository.starts_with("http://") {
        let authority = source
            .repository
            .split("://")
            .nth(1)
            .unwrap_or("")
            .split('/')
            .next()
            .unwrap_or("");
        ensure!(
            !authority.contains('@'),
            "do not embed credentials in source URLs; use Git authentication"
        );
    }
    ensure!(
        !source.reference.is_empty() && !source.reference.starts_with('-'),
        "invalid Git ref"
    );
    Ok(())
}

pub fn validate_manifest(manifest: &Manifest) -> Result<()> {
    ensure!(
        manifest.format == 1,
        "unsupported manifest format {}",
        manifest.format
    );
    for package in &manifest.packages {
        name(package)?;
        ensure!(
            !manifest.dependencies.contains_key(package),
            "{package} is both local and imported"
        );
    }
    for (alias, source) in &manifest.sources {
        name(alias)?;
        validate_source(source)?;
    }
    for (package, source) in &manifest.dependencies {
        name(package)?;
        ensure!(
            manifest.sources.contains_key(source),
            "unknown source {source} for {package}"
        );
    }
    Ok(())
}

pub fn package(tree: &Tree, expected: &str) -> Result<Package> {
    let manifest: Package = decode(tree.get("package.toml").context("missing package.toml")?)?;
    name(&manifest.name)?;
    ensure!(
        manifest.name == expected,
        "package {expected} declares name {}",
        manifest.name
    );
    ensure!(
        !manifest.owner.trim().is_empty(),
        "package {expected} needs an owner"
    );
    for dependency in &manifest.dependencies {
        name(dependency)?;
    }
    Ok(manifest)
}

pub fn read_tree(root: &Path) -> Result<Tree> {
    fn visit(root: &Path, path: &Path, tree: &mut Tree, size: &mut usize) -> Result<()> {
        let metadata = fs::symlink_metadata(path)?;
        ensure!(
            !metadata.file_type().is_symlink(),
            "symlinks are not supported: {}",
            path.display()
        );
        if metadata.is_dir() {
            for entry in fs::read_dir(path)? {
                visit(root, &entry?.path(), tree, size)?;
            }
        } else {
            ensure!(metadata.is_file(), "not a regular file: {}", path.display());
            let relative = path
                .strip_prefix(root)?
                .to_str()
                .context("non-UTF-8 path")?
                .replace(std::path::MAIN_SEPARATOR, "/");
            safe_path(&relative)?;
            ensure!(
                metadata.len() <= MAX_FILE as u64,
                "{} exceeds 16 MiB",
                path.display()
            );
            *size += metadata.len() as usize;
            ensure!(*size <= MAX_TREE, "knowledge directory exceeds 256 MiB");
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                ensure!(
                    metadata.permissions().mode() & 0o111 == 0,
                    "executable package files are not supported: {}",
                    path.display()
                );
            }
            tree.insert(relative, fs::read(path)?);
        }
        Ok(())
    }
    let mut tree = Tree::new();
    visit(root, root, &mut tree, &mut 0)?;
    Ok(tree)
}

pub fn write_tree(root: &Path, tree: &Tree) -> Result<()> {
    let mut paths = BTreeMap::new();
    for path in tree.keys() {
        safe_path(path)?;
        let mut prefix = String::new();
        let parts: Vec<_> = path.split('/').collect();
        for (index, part) in parts.iter().enumerate() {
            if !prefix.is_empty() {
                prefix.push('/');
            }
            prefix.push_str(part);
            let entry = (prefix.clone(), index + 1 == parts.len());
            if let Some(previous) = paths.insert(prefix.to_lowercase(), entry.clone()) {
                ensure!(
                    previous == entry,
                    "package paths collide on a case-insensitive filesystem: {}",
                    prefix
                );
            }
        }
    }
    fs::create_dir_all(root)?;
    for (path, bytes) in tree {
        safe_path(path)?;
        let target = root.join(path);
        fs::create_dir_all(target.parent().context("missing parent")?)?;
        fs::write(target, bytes)?;
    }
    Ok(())
}

pub fn subtree(tree: &Tree, prefix: &str) -> Tree {
    let prefix = format!("{prefix}/");
    tree.iter()
        .filter_map(|(path, bytes)| {
            path.strip_prefix(&prefix)
                .map(|relative| (relative.to_owned(), bytes.clone()))
        })
        .collect()
}

pub fn replace_subtree(tree: &mut Tree, prefix: &str, replacement: &Tree) {
    let prefix = format!("{prefix}/");
    tree.retain(|path, _| !path.starts_with(&prefix));
    tree.extend(
        replacement
            .iter()
            .map(|(path, bytes)| (format!("{prefix}{path}"), bytes.clone())),
    );
}

pub fn without_generated_indexes(tree: &Tree) -> Tree {
    tree.iter()
        .filter(|(path, bytes)| {
            !(path.rsplit('/').next() == Some("index.md") && is_generated_index(bytes))
        })
        .map(|(path, bytes)| (path.clone(), bytes.clone()))
        .collect()
}

pub fn is_generated_index(bytes: &[u8]) -> bool {
    let text = String::from_utf8_lossy(bytes);
    text.contains(MARKER) || text.contains("<!-- Generated by gnosis. -->")
}

fn directory_metadata(path: &str, bytes: &[u8]) -> Result<Mapping> {
    let parse = || -> Result<Mapping> {
        let value: Value = serde_yaml_ng::from_slice(bytes)?;
        let mapping = value
            .as_mapping()
            .context("directory metadata must be a YAML mapping")?;
        for key in ["type", "title", "description"] {
            if let Some(value) = mapping.get(key) {
                let text = value
                    .as_str()
                    .with_context(|| format!("{key} must be a string"))?;
                if key != "description" {
                    ensure!(!text.trim().is_empty(), "{key} must not be empty");
                }
                if key == "title" {
                    ensure!(!text.contains(['\n', '\r']), "title must be a single line");
                }
            }
        }
        Ok(mapping.clone())
    };
    parse().with_context(|| format!("invalid directory metadata {path}"))
}

fn frontmatter(text: &str) -> Result<Option<Value>> {
    let normalized = text.replace("\r\n", "\n");
    let Some(rest) = normalized.strip_prefix("---\n") else {
        return Ok(None);
    };
    let mut yaml = String::new();
    for line in rest.lines() {
        if line == "---" {
            return Ok(Some(serde_yaml_ng::from_str(&yaml)?));
        }
        yaml.push_str(line);
        yaml.push('\n');
    }
    bail!("unterminated YAML frontmatter")
}

pub fn validate_okf(tree: &Tree) -> Result<()> {
    for (path, bytes) in tree {
        safe_path(path)?;
        if path.rsplit('/').next() == Some("index.yml") {
            directory_metadata(path, bytes)?;
        }
        if !path.ends_with(".md") {
            continue;
        }
        let check = || -> Result<()> {
            let text = std::str::from_utf8(bytes)?;
            let metadata = frontmatter(text)?;
            match path.rsplit('/').next() {
                Some("index.md") => {
                    if let Some(metadata) = metadata {
                        ensure!(path == "index.md", "nested indexes cannot have frontmatter");
                        let mapping = metadata
                            .as_mapping()
                            .context("index frontmatter must be a mapping")?;
                        ensure!(
                            mapping.len() == 1
                                && mapping.get("okf_version").and_then(Value::as_str)
                                    == Some("0.2"),
                            "root index frontmatter must contain only okf_version: \"0.2\""
                        );
                    }
                }
                Some("log.md") => ensure!(metadata.is_none(), "log.md cannot have frontmatter"),
                _ => {
                    let metadata = metadata.context("concept needs YAML frontmatter")?;
                    let mapping = metadata
                        .as_mapping()
                        .context("frontmatter must be a mapping")?;
                    ensure!(
                        mapping
                            .get("type")
                            .and_then(Value::as_str)
                            .is_some_and(|s| !s.trim().is_empty()),
                        "concept needs a nonempty string type"
                    );
                }
            }
            Ok(())
        };
        check().with_context(|| format!("invalid OKF document {path}"))?;
    }
    Ok(())
}

pub fn escape(text: &str) -> String {
    text.replace(['\n', '\r'], " ")
        .replace('\\', "\\\\")
        .replace('[', "\\[")
        .replace(']', "\\]")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn url(path: &str) -> String {
    path.bytes()
        .map(|byte| {
            if byte.is_ascii_alphanumeric() || b"-._~/".contains(&byte) {
                (byte as char).to_string()
            } else {
                format!("%{byte:02X}")
            }
        })
        .collect()
}

fn index_entry(title: &str, path: &str, description: &str) -> String {
    let suffix = if description.is_empty() {
        String::new()
    } else {
        format!(" - {}", escape(description))
    };
    format!("* [{}]({}){suffix}\n", escape(title), url(path))
}

pub fn indexes(tree: &mut Tree, title: &str) -> Result<()> {
    validate_okf(tree)?;
    let metadata: BTreeMap<_, _> = tree
        .iter()
        .filter(|(path, _)| path.rsplit('/').next() == Some("index.yml"))
        .map(|(path, bytes)| Ok((path.clone(), directory_metadata(path, bytes)?)))
        .collect::<Result<_>>()?;
    let mut directories = BTreeSet::from([String::new()]);
    for path in tree.keys() {
        let mut parent = Path::new(path).parent();
        while let Some(directory) = parent {
            let directory = directory.to_str().context("non-UTF-8 directory")?;
            if directory.is_empty() {
                break;
            }
            directories.insert(directory.to_owned());
            parent = Path::new(directory).parent();
        }
    }
    for directory in directories.iter().rev() {
        let prefix = if directory.is_empty() {
            String::new()
        } else {
            format!("{directory}/")
        };
        let target = format!("{prefix}index.md");
        if tree
            .get(&target)
            .is_some_and(|bytes| !is_generated_index(bytes))
        {
            continue;
        }
        let mut entries = BTreeMap::new();
        for (path, bytes) in tree.iter() {
            let Some(relative) = path.strip_prefix(&prefix) else {
                continue;
            };
            if relative.contains('/') {
                let child = relative
                    .split('/')
                    .next()
                    .context("missing child directory")?;
                if tree.contains_key(&format!("{prefix}{child}/index.md")) {
                    let child_metadata = metadata.get(&format!("{prefix}{child}/index.yml"));
                    let child_title = child_metadata
                        .and_then(|fields| fields.get("title"))
                        .and_then(Value::as_str)
                        .unwrap_or(child);
                    let description = child_metadata
                        .and_then(|fields| fields.get("description"))
                        .and_then(Value::as_str)
                        .unwrap_or("");
                    entries.insert(
                        format!("{child}/"),
                        index_entry(child_title, &format!("{child}/index.md"), description),
                    );
                }
            } else if relative.ends_with(".md") && relative != "index.md" && relative != "log.md" {
                let metadata =
                    frontmatter(std::str::from_utf8(bytes)?)?.context("missing frontmatter")?;
                let title = metadata
                    .get("title")
                    .and_then(Value::as_str)
                    .unwrap_or(relative.trim_end_matches(".md"));
                let description = metadata
                    .get("description")
                    .and_then(Value::as_str)
                    .unwrap_or("");
                entries.insert(
                    relative.to_owned(),
                    index_entry(title, relative, description),
                );
            }
        }
        let default_heading = if directory.is_empty() {
            title
        } else {
            directory
        };
        let own_metadata = metadata.get(&format!("{prefix}index.yml"));
        let heading = own_metadata
            .and_then(|fields| fields.get("title"))
            .and_then(Value::as_str)
            .unwrap_or(default_heading);
        let description = own_metadata
            .and_then(|fields| fields.get("description"))
            .and_then(Value::as_str)
            .unwrap_or("");
        let description = if description.is_empty() {
            String::new()
        } else {
            format!("{}\n\n", escape(description))
        };
        let header = if directory.is_empty() {
            "---\nokf_version: \"0.2\"\n---\n"
        } else {
            ""
        };
        tree.insert(
            target,
            format!(
                "{header}{MARKER}\n\n# {}\n\n{description}{}",
                escape(heading),
                entries.values().cloned().collect::<String>()
            )
            .into_bytes(),
        );
    }
    Ok(())
}

pub fn root_index(tree: &mut Tree, packages: &BTreeSet<String>) -> Result<()> {
    if tree
        .get("index.md")
        .is_some_and(|bytes| !is_generated_index(bytes))
    {
        return Ok(());
    }
    let mut body = format!("{MARKER}\n\n# Knowledge packages\n\n");
    for name in packages {
        let package = package(&subtree(tree, name), name)?;
        body.push_str(&format!(
            "* [{name}]({name}/index.md) - {}\n",
            escape(&package.description)
        ));
    }
    tree.insert("index.md".into(), body.into_bytes());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_trees_reject_case_and_directory_collisions_before_writing() {
        for names in [["Facts.md", "facts.md"], ["Folder", "folder/fact.md"]] {
            let directory = tempfile::tempdir().unwrap();
            let tree = names
                .into_iter()
                .map(|name| (name.to_owned(), b"content".to_vec()))
                .collect();
            assert!(write_tree(directory.path(), &tree).is_err());
            assert_eq!(fs::read_dir(directory.path()).unwrap().count(), 0);
        }
    }
}
