use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use anyhow::{Context, Result};
use serde_yaml_ng::Value;

use crate::metadata::package;
use crate::okf::{directory_metadata, escape, frontmatter, validate_okf};
use crate::tree::{Tree, subtree};

pub const MARKER: &str = "<!-- Generated by gnosis -->";

pub fn without_generated_indexes(tree: &Tree) -> Tree {
    tree.iter()
        .filter(|(path, bytes)| {
            !(path.rsplit('/').next() == Some("index.md") && is_generated_index(bytes))
        })
        .map(|(path, bytes)| (path.clone(), bytes.clone()))
        .collect()
}

pub fn is_generated_index(bytes: &[u8]) -> bool {
    let text = String::from_utf8_lossy(bytes);
    text.contains(MARKER) || text.contains("<!-- Generated by gnosis. -->")
}

fn url(path: &str) -> String {
    path.bytes()
        .map(|byte| {
            if byte.is_ascii_alphanumeric() || b"-._~/".contains(&byte) {
                (byte as char).to_string()
            } else {
                format!("%{byte:02X}")
            }
        })
        .collect()
}

fn index_entry(title: &str, path: &str, description: &str) -> String {
    let suffix = if description.is_empty() {
        String::new()
    } else {
        format!(" - {}", escape(description))
    };
    format!("* [{}]({}){suffix}\n", escape(title), url(path))
}

pub fn indexes(tree: &mut Tree, title: &str) -> Result<()> {
    validate_okf(tree)?;
    let metadata: BTreeMap<_, _> = tree
        .iter()
        .filter(|(path, _)| path.rsplit('/').next() == Some("index.yml"))
        .map(|(path, bytes)| Ok((path.clone(), directory_metadata(path, bytes)?)))
        .collect::<Result<_>>()?;
    let mut directories = BTreeSet::from([String::new()]);
    for path in tree.keys() {
        let mut parent = Path::new(path).parent();
        while let Some(directory) = parent {
            let directory = directory.to_str().context("non-UTF-8 directory")?;
            if directory.is_empty() {
                break;
            }
            directories.insert(directory.to_owned());
            parent = Path::new(directory).parent();
        }
    }
    for directory in directories.iter().rev() {
        let prefix = if directory.is_empty() {
            String::new()
        } else {
            format!("{directory}/")
        };
        let target = format!("{prefix}index.md");
        if tree
            .get(&target)
            .is_some_and(|bytes| !is_generated_index(bytes))
        {
            continue;
        }
        let mut entries = BTreeMap::new();
        for (path, bytes) in tree.iter() {
            let Some(relative) = path.strip_prefix(&prefix) else {
                continue;
            };
            if relative.contains('/') {
                let child = relative
                    .split('/')
                    .next()
                    .context("missing child directory")?;
                if tree.contains_key(&format!("{prefix}{child}/index.md")) {
                    let child_metadata = metadata.get(&format!("{prefix}{child}/index.yml"));
                    let child_title = child_metadata
                        .and_then(|fields| fields.get("title"))
                        .and_then(Value::as_str)
                        .unwrap_or(child);
                    let description = child_metadata
                        .and_then(|fields| fields.get("description"))
                        .and_then(Value::as_str)
                        .unwrap_or("");
                    entries.insert(
                        format!("{child}/"),
                        index_entry(child_title, &format!("{child}/index.md"), description),
                    );
                }
            } else if relative.ends_with(".md") && relative != "index.md" && relative != "log.md" {
                let metadata =
                    frontmatter(std::str::from_utf8(bytes)?)?.context("missing frontmatter")?;
                let title = metadata
                    .get("title")
                    .and_then(Value::as_str)
                    .unwrap_or(relative.trim_end_matches(".md"));
                let description = metadata
                    .get("description")
                    .and_then(Value::as_str)
                    .unwrap_or("");
                entries.insert(
                    relative.to_owned(),
                    index_entry(title, relative, description),
                );
            }
        }
        let default_heading = if directory.is_empty() {
            title
        } else {
            directory
        };
        let own_metadata = metadata.get(&format!("{prefix}index.yml"));
        let heading = own_metadata
            .and_then(|fields| fields.get("title"))
            .and_then(Value::as_str)
            .unwrap_or(default_heading);
        let description = own_metadata
            .and_then(|fields| fields.get("description"))
            .and_then(Value::as_str)
            .unwrap_or("");
        let description = if description.is_empty() {
            String::new()
        } else {
            format!("{}\n\n", escape(description))
        };
        let header = if directory.is_empty() {
            "---\nokf_version: \"0.2\"\n---\n"
        } else {
            ""
        };
        tree.insert(
            target,
            format!(
                "{header}{MARKER}\n\n# {}\n\n{description}{}",
                escape(heading),
                entries.values().cloned().collect::<String>()
            )
            .into_bytes(),
        );
    }
    Ok(())
}

pub fn root_index(tree: &mut Tree, packages: &BTreeSet<String>) -> Result<()> {
    if tree
        .get("index.md")
        .is_some_and(|bytes| !is_generated_index(bytes))
    {
        return Ok(());
    }
    let mut body = format!("{MARKER}\n\n# Knowledge packages\n\n");
    for name in packages {
        let package = package(&subtree(tree, name), name)?;
        body.push_str(&format!(
            "* [{name}]({name}/index.md) - {}\n",
            escape(&package.description)
        ));
    }
    tree.insert("index.md".into(), body.into_bytes());
    Ok(())
}
